### ISSUE TITLE
UML State diagrams and activity diagrams

### ISSUE THREAD

**Issue by leeyat1** [Ree347/Group7#18]
Create a UML State diagram for each User Story 
Chalmers 1-3 
Pranavi 4-6
Ree 7-9
Leeya - 10

**Comment by leeyat1** [comment]
Completed for user story 10

**Comment by Ree347** [comment]
Completed 7-9

**Comment by PranaviBeerelli** [comment]
Completed for user stories 4-6

**Comment by Chalmers4** [comment]
completed 1-3
